module.exports = [
    {
        "createBy": null,
        "createTime": "2023-04-23 16:11:46",
        "updateBy": null,
        "updateTime": null,
        "remark": "超级管理员",
        "roleId": 0,
        "roleName": "超级管理员",
        "roleKey": "admin",
        "roleSort": 1,
        "dataScope": "1",
        "menuCheckStrictly": true,
        "deptCheckStrictly": true,
        "status": "0",
        "delFlag": "0",
        "flag": false,
        "menuIds": null,
        "deptIds": null,
        "permissions": null,
        "admin": true
    },
    {
        "createBy": null,
        "createTime": "2023-04-23 16:11:46",
        "updateBy": null,
        "updateTime": null,
        "remark": "系统管理员",
        "roleId": 1,
        "roleName": "系统管理员",
        "roleKey": "admin",
        "roleSort": 1,
        "dataScope": "1",
        "menuCheckStrictly": true,
        "deptCheckStrictly": true,
        "status": "0",
        "delFlag": "0",
        "flag": false,
        "menuIds": null,
        "deptIds": null,
        "permissions": null,
        "admin": true
    },
    {
        "createBy": null,
        "createTime": "2023-04-23 16:11:46",
        "updateBy": null,
        "updateTime": null,
        "remark": "普通用户",
        "roleId": 2,
        "roleName": "普通用户",
        "roleKey": "admin",
        "roleSort": 1,
        "dataScope": "1",
        "menuCheckStrictly": true,
        "deptCheckStrictly": true,
        "status": "0",
        "delFlag": "0",
        "flag": false,
        "menuIds": null,
        "deptIds": null,
        "permissions": null,
        "admin": true
    }
];
